version: "3.9"

services:
  rustapp:
    container_name: rustapp
    image: francescoxx/rustapp:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://timdb_user:7BEEZBEFepTJizYHIjLkX4N587ZoVwNr@dpg-ck20iu7hdsdc73e02bhg-a.oregon-postgres.render.com/timdb
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=timdb_user
      - POSTGRES_PASSWORD=7BEEZBEFepTJizYHIjLkX4N587ZoVwNr
      - POSTGRES_DB=timdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
