version: "3.9"

services:
  rustapp:
    container_name: rustapp
    image: francescoxx/rustapp:1.0.0
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://timdb_user:7BEEZBEFepTJizYHIjLkX4N587ZoVwNr@dpg-ck20iu7hdsdc73e02bhg-a.oregon-postgres.render.com/timdb

volumes:
  pgdata: {}
