version: "3.9"

services:
  rustapp:
    container_name: rustapp
    image: francescoxx/rustapp:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://timdb_ifhr_user:HHrTEB1pMXRQF3tWTxZT6fuPAZiRGMhz@dpg-ck2mlnfqj8ts73fb4id0-a.oregon-postgres.render.com/timdb_ifhr
